<?php include "menu.phtml";?>
<div class="d1 container-fluid">
<div class="row">    
    <div class="headdiv col-lg-3 col-md-4 col-sm-5">
        <?php include "userHead.phtml"; ?>
    </div>
    <div class="d2 col-lg-5 col-md-6 col-sm-6">
        <?php if (isset($error) && !empty($error)): ?>
        <?php foreach ($error as $val): ?>
                <?=$val; ?><br/>
            <?php endforeach; ?>
        <?php endif; ?>
        <hr>

    <?php if ($idAlbum==''): ?>
        <!--Альбомы-->
        <?php if ( ($iduser==$idUserWall) ) : ?>
            <form action="/foto/<?=$iduser?>/" method ="POST">
                <input type='text' name='newAlbum' placeholder="Название альбома"/>
                <input class='btn btn-primary' type='submit' value='Создать альбом'>
            </form>
            <hr>
        <?php endif; ?>
        
        <?php foreach ($arrOut as $v): ?>
            
            <a href="/foto/<?=$idUserWall?>/album/<?=$v['id']?>/">
            <?=$v['name']?><br/>
            
                <?=getAvaAlbum($v['id'],$idUserWall)?>
            
            </a>
            
            <?php if ( ($iduser==$idUserWall) ) : ?>
                <div class=right>
                <a  href="/foto/<?=$iduser?>/delAlbum/<?=$v['id'];?>/">
                <button class='btn btn-default' title='Удалить альбом'><img src='/static/delete.png'></button>
                </a>
                </div>
            <?php endif; ?>
            <hr>
        <?php endforeach; ?>

    <?php else: ?>
        
        <!--фотографии в альбоме-->
        <?php if ( ($iduser==$idUserWall) ) : ?>
            <form action='/foto/<?=$iduser?>/album/<?=$idAlbum?>/' method="post" enctype="multipart/form-data">
                <input type="hidden" name="MAX_FILE_SIZE" value="5000000" />
                <input type="file" name="newFoto"/>
                <br/><br/>
                <input class='btn btn-primary' type="submit" value="Добавить фото"/>
            </form>
        <?php endif; ?>
        <hr>        



        <?php include "slide3.phtml";?>


    <?php endif; ?>

    </div>
    
</div>
</div>