<?php include "menu.phtml";?>
<div class='d1'>

    <?php include "userHead.phtml"; ?>

<div class='d2' onclick=getEvent(event)>
<?php if ( ($iduser==$idUserWall) ) : ?>
    <form action='/friends/<?=$iduser?>/find/' method='POST'>
            <input class='b3' type='submit' value='поиск'>
    </form>
<hr>
<?php endif; ?> 


<!--если режим поиска пользователя-->
<?php if ($find!=''): ?>
    <form action='/friends/<?=$iduser?>/find/' method='POST'>
     Имя:<input name='find_user_name' type='text' value='<?=$findName?>'><br/>
     Фамилия:<input name='find_user_sname' type='text' value='<?=$findSName?>'><br/>
     <input class='b3' type='submit' value='ok'>
    </form>
    <hr>
    <?php foreach ($arrFindUser as $v): ?>
            <div>
                <a href="/user/<?=$v['id_user'];?>/"><?=$v['name'];?> <?=$v['second_name'];?>
                    <div><?=getAva($v['id_user'])?></div>
                </a>
                    <form class='right' action='/friends/' method ='POST'>
                    <button class='b3' title='Добавить в друзья'><img src='/static/add.png'></button>
                    <input name='requestAddFriend' class='hidden' value='<?=$v['id_user'];?>'>
                    </form>

            </div><hr>
    <?php endforeach; ?>

<?php else : ?>

    <!--входящие заявки в друзья-->
    <?php if (!empty($friends_requests)): ?>
        <b>Новые заявки в друзья к <?=$name?> <?=$secondName?>:</b><hr>
        <?php foreach ($friends_requests as $v): ?>
            <div class='friends_requests'>
                <a  href="/user/<?=$v['id_user'];?>/">
                    <b><?=$v['name'];?> <?=$v['second_name'];?></b>
                    <div><?=getAva($v['id_user'])?></div>
                </a>
                <input name='id_request_Friend' class='hidden' value='<?=$v['id'];?>'>
            </div>
                <div class='right'>
                    <a  href="/friends/<?=$iduser;?>/addf/<?=$v['id_user'];?>/">
                    <button class='b3 right' title='Добавить в друзья'><img src='/static/add.png'></button>
                    </a>
                    <a  href="/friends/<?=$iduser;?>/delr/<?=$v['id_req'];?>/">
                    <button class='b3 right' title='Отклонить заявку'><img src='/static/delete.png'></button>
                    </a>
                </div>
            <hr>
        <?php endforeach; ?>
    <?php endif; ?> 

    <!--заявки от пользоваетля-->
    <?php if (!empty($my_requests)): ?>
        <b>Заявки <?=$name?> <?=$secondName?> к пользователям:</b><hr>
        <?php foreach ($my_requests as $v): ?>
            <div class='friends_requests'>
                <a  href="/user/<?=$v['id_friend'];?>/">
                    <b><?=$v['name'];?> <?=$v['second_name'];?></b>
                    <div><?=getAva($v['id_friend'])?></div>
                </a>
            </div>
                <div class='right'>
                    <a  href="/friends/<?=$iduser;?>/delmyr/<?=$v['id_req'];?>/">
                    <button class='b3 right' title='Отклонить заявку'><img src='/static/delete.png'></button>
                    </a>
                </div>
            <hr>
        <?php endforeach; ?>
    <?php endif; ?> 

    <!--вывод списка друзей-->
    <b>Друзья</b><hr>
    <?php foreach ($arrOut as $v): ?>
        <div>
            <a  href="/user/<?=$v['idfriend'];?>/">
                <b><?=$v['name'];?> <?=$v['second_name'];?></b>
                <div><?=getAva($v['idfriend'])?></div>
            </a><?=getOnline($v['online']);?>

                <div class='right'><a  href="/msg/<?=$v['idfriend'];?>/">
                    <button class='b3 right' title='Отправить сообщение'><img src='/static/msg.png'></button>
                    </a>
                    <?php if ( ($iduser==$idUserWall) ) : ?>
                        <form  action='/friends/' method ='POST'>
                            <input name='idDelFriend' class='hidden' value='<?=$v['idfriend'];?>'>  
                            <button class='b3 right' title='Удалить из друзей'><img src='/static/delete.png'></button>
                        </form>
                   <?php endif; ?>         
                </div>
        </div><hr>
    <?php endforeach; ?>
<?php endif; ?>
</div>
</div>