<div class='login'>
    <form action="login/" method ="POST">
        <input name ="login" type="text" placeholder="Имя пользоваля"><br/>
        <input name ="password" type="password" placeholder="Пароль"><br/><br/>
        <input class='b1' type="submit" value="Войти">
    </form>    
    <hr>
    <form action="reg/" method ="POST">    
        <input class='b1' type="submit" value="Регистрация"><br/>
    </form>
</div>