<div class='menu'>
    <table>
        <tr class='trmenu'><td><a href='/user/'><?="Пользователь:".$user?></a></td></tr>
        <tr class='trmenu'><td><a href='/friends/'>Друзья</a></td></tr>
        <tr class='trmenu'><td><a href='/msg/'>Сообщения</a></td></tr>
        <tr class='trmenu'><td><a href='/news/'>Новости</a></td></tr>
    </table>
    <br/><br/>

<form action="/exit/" method ="POST">
<input class='b2' type="submit" value="Выход">    
</form>
</div>