<div id="menu" class="menu navbar-top" onclick="getEvent(event)">
<div class="container">
    <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu">
        <span class="glyphicon glyphicon-align-justify"></span>
        </button>
    </div>    
    <div class="collapse navbar-collapse" id="responsive-menu">
        <ul class='nav navbar-nav'>
        <li><a href='/user/'>Моя страница</a></li>
        <li><a href='/friends/' id='newFriends'>Друзья</a></li>
        <li><a href='/msg/' id='newMessages'>Сообщения</a></li>
        <li><a href='/foto/'>Фотоальбомы</a></li>
        <!--<a href='/news/'><div>Новости</div></a>-->
        <li><a href='/settings/'>Настройки</a></li>
        <li><a href='/exit/'>Выход</a></li>
        </ul>
    </div>
</div>
</div>
