<div class='menu'>
    
        <a href='/user/'><div class='trmenu'>Моя страница</div></a>
        <a href='/friends/'><div class='trmenu'>Друзья</div></a>
        <a href='/msg/'><div class='trmenu'>Сообщения</div></a>
        <a href='/news/'><div class='trmenu'>Новости</div></a>
        <a href='/settings/'><div class='trmenu'>Настройки</div></a>    
    <br/><br/>

<form action="/exit/" method ="POST">
<input class='b2' type="submit" value="Выход">    
</form>
</div>