<?php include "menu.phtml"; ?>
<div class="d1" onclick=getEvent(event)>
    <div class="headdiv" id="headnews">Сообщения</div>



    <div class="d2">
        <!-- если выбран диалог -->
        <?php if ($idFriend!=''): ?>
            Диалог с <?=$logFriend?><input class='hidden' id='idfriend' value='<?=$idFriend?>'> <hr>

            <div class="dialog" id="dialog">
            </div>

                <textarea class="msgtext" placeholder="текст сообщения" id="newMsg" name="newMsg"/></textarea>
                <br><input class="b1" type="button" id='sendMsg' value="Отправить">
    
        <?php else: ?>
            
        <!-- список диалогов -->

                <?php foreach ($arrOut as $v): ?>
                    <div>
                        <a href="/msg/?idf=<?=$v['id_friend']?>"><b><?=$v['friend']?></b></a>
                    </div>
                    <br/>
                <?php endforeach; ?>

        <?php endif; ?>
    </div>
</div>
