<?php include "menu.phtml"; ?>
<div class="d1">
    <div class="headdiv" id="headnews">Сообщения</div>



    <div class="d2">
        <!-- если выбран диалог -->
        <?php if ($idFriend!=''): ?>
            Диалог с <?=$logFriend?><input class='hidden' id='idfriend' value='<?=$idFriend?>'> <hr>
            <div class="dialog" id="dialog">



            </div>

            <form action="/msg/?idf=<?=$idFriend?>" method ="POST">
                <textarea class="msgtext" placeholder="текст сообщения" name="newMsg"/></textarea>
                <br><input class="b1" type="submit" value="Отправить">
            </form>    
        <?php else: ?>
            
        <!-- список диалогов -->
            <table>
                <?php foreach ($arrOut as $v): ?>
                    <tr>
                        <td><a href="/msg/?idf=<?=$v['idfriend']?>"><b><?=$v['friend']?></b></a></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        <?php endif; ?>
    </div>
</div>
