<?php include "menu.phtml"; ?>
<div class="d1" onclick=getEvent(event)>

    <?php include "userHead.phtml"; ?>

    <div class="d2">
        <!-- если выбран диалог -->
        <?php if ($idFriend!=''): ?>
            <input class='hidden' id='idfriend' value='<?=$idFriend?>'>
                Диалог с <a  href="/user/<?=$idFriend;?>/"><b><?=$logFriend?></b></a>
                <div class='right'><?=$onlineFriend?></div>
            
            <hr>
            <div class="dialog" id="dialog">
            </div>

                <textarea class="msgtext" placeholder="текст сообщения" id="newMsg" name="newMsg"/></textarea>
                <br><input class="b1" type="button" id='sendMsg' value="Отправить">
    
        <?php else: ?>
            
        <!-- список диалогов -->
                Диалоги
                <hr>
                <?php foreach ($arrOut as $v): ?>
                    <div>
                        <a href="/msg/<?=$v['id_friend']?>/"><b><?=$v['friend']?></b>
                        <div><?=getAva($v['id_friend'])?>
                        
                        <?php if ($kolNewMsg[$v['id_friend']]) : ?> 
                                Новые сообщения:<?=($kolNewMsg[$v['id_friend']])?>
                        <?php endif; ?>
                        </div>
                        
                        </a>
                            <?=getOnline($v['online'])?>
                    </div>
                    <hr>
                <?php endforeach; ?>

        <?php endif; ?>
    </div>
</div>
