<?php
session_start();
require "../core/config.php";
require "../core/db.php";
require "../core/func.php";

$idFriend="";
if (isset($_GET['idf'])) {
    $idFriend=$_GET['idf'];
}
$prizn=$_GET['prizn']; //признак первого считывания сообщений из диалога
$iduser=$_SESSION['iduser'];
$arrOut=readMsg($db,$iduser,$idFriend,$prizn);
?>

<?php foreach ($arrOut as $v): ?>
    <?php if ($v['id_user']==$v['id_autor']): ?>
        <div align=left>
    <?php else: ?>
        <div align=right>
    <?php endif; ?>
            <b><?=out($v['autor'])?></b> &nbsp <?=$v['date'] ?><br/>
            <?=out($v['text'])?>
        </div><br/>
<?php endforeach; ?>



