<?php include "menu.phtml"; ?>

<div class='d1' onclick=getEvent(event)>
        <div class='headdiv' id='headnews'>Новости
            <img id='addNews' src='/static/add.png' title='Добавить'>
        </div>
        <div class='d2'>
            <table>
                <?php if (isset($arr_out)): ?>
                    <?php foreach ($arr_out as $v): ?>
                        <tr>
                            <th class='trnews' id='<?=$v['id']?>'>
                            <?=$v['data'].' '.$v['autor']; ?>
                            </th>
                            <th>
                            <div class='hidden' id='news<?=$v['id']?>'></div>
                            </th>
                        </tr>
                        <tr><td>
                            <?=$v['text']; ?>
                            <hr>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
        </div>
</div>        