<?php $i=0; if (isset($error)): ?>
    <?php foreach ($error as $val): ?>
        <font color="#C0AFAB"><?=++$i.'.'.$val; ?></font><br/>
    <?php endforeach; ?>
<hr>
<?php endif;?>
<?php if ($regfl==0):?>
    <div class='reg'>
    <form action="../reg/" method ="POST">
        <br/><input name ="login" type="text" placeholder="Логин" value='<?= $login ?>'><br/>
        <br/><input name ="email" type="text" placeholder="e-mail" value='<?= $email ?>'><br/>
        <br/><input name ="password" type="password" placeholder="Пароль"><br/>
        <br/><input name ="password1" type="password" placeholder="Подтвердите пароль"><br/>
        <br/><input class='b1' type="submit" value="Ок">
    </form>
        <form action="../" method ="POST">
        <br/><input class='b1' type="submit" value="Главная страница">
        </form>
    </div>
<?php else: ?>
    <b>Пользователь <?= $login ?> зарегистрирован.</b>
        <form action="../" method ="POST">
        <br/><input class='b1' type="submit" value="Ок">
    </form>
<?php endif; ?>


