<?php include "menu.phtml"; ?>


<div class="d1">

    <!--Вывод ошибок-->
    <?php if (isset($error) && !empty($error)): ?>
        <?php foreach ($error as $val): ?>
            <font color="#C0AFAB"><?=$val; ?></font><br/>
        <?php endforeach; ?>
    <hr>
    <?php endif; ?>

<div class="d2">
    Настройки профиля <?=$user?>
    
    <hr>
    <!--настройка аватарки-->
    <div><?=getAva($iduser)?></div>
    <form action="/settings/" method="post" enctype="multipart/form-data">
        <input type="hidden" name="MAX_FILE_SIZE" value="500000" />
        <input type="file" name="userfile"/>
        <br/><br/>
        <input class="b1" type="submit" value="Обновить аватар"/>
    </form>
    <hr>
    <!--настройка ФИО-->
    <form action="/settings/" method="post">
        <input name ="name" type="text" placeholder="Имя" value="<?= $name ?>"><br/>
        <br/><input name ="secondName" type="text" placeholder="Фамилия" value="<?= $secondName ?>"><br/>
        <br/>Дата рождения:
        <input name="day" type="text" placeholder="д." 
               pattern="[0-9]{2}" style='width:20px' value="<?=$day?>"> -
        <input name ="month" type="text" value="<?= $month ?>" value="" placeholder="м." maxlength=2 pattern="[0-9]{2}"
            style='width:20px'>-
        <input name ="year" type="text" value="<?= $year ?>" placeholder="год" maxlength=4 pattern="[0-9]{4}" style='width:40px'>
        <br/><br/>
        <input class="b1" type="submit" value="Сохранить"/>
        </form>        
        
</div>
</div>