<?php include "menu.phtml"; ?>

<div class="d1" onclick=getEvent(event)>

    <?php include "userHead.phtml"; ?>

    <div class="d2">
        <div><button id="addNews" class='b3' title="Добавить запись">Добавить запись</button>
        </div>
        <hr>
            <?php foreach ($arr_out as $v): ?>
                        
                    <div  class='trnews divleft'>
                        <a  href="/user/<?=$v['id_autor'];?>/">
                             <?=$v['autor']?>  
                        </a>
                    </div>
                    <?php if ( ($iduser==$v['id_autor']) || ($iduser==$idUserWall) ) : ?>    
                        <div  class='divleft' id='news<?=$v['id']?>'></div>
                    <?php endif; ?>
                        
                    <div class='trwall clearleft' id='<?=$v['id']?>'>
                        <br/><?=$v['text']; ?><br/>
                    </div>
                    <div>    
                        <p><?=$v['date']; ?></p>
                    </div>
                    <hr>
            <?php endforeach; ?>
</div>        