    <b><a  href="/user/<?=$idUserWall;?>/"
        <b><?=$name?> <?=$secondName?></b><br/>
        <?=getAva($idUserWall)?><br/>
    </a>
    <?=$online?></b>
   
    <?php if ( ($iduser!=$idUserWall) ) : ?>    
        <a  href="/msg/<?=$idUserWall;?>/">
        <button class='btn btn-default' title='Отправить сообщение'>
            <span class="glyphicon glyphicon-envelope"></span>
        </button>
        </a>
    <?php endif; ?>
    <a  href="/friends/<?=$idUserWall;?>/"><button class="btn btn-primary">Друзья</button></a>
    <a  href="/foto/<?=$idUserWall;?>/"><button class="btn btn-primary">Фото</button></a>
    <input type="text" id="idUserWall" class='hidden' value="<?=$idUserWall?>"/>