<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        <?php if(isset($title)):?>
            <?=$title;?>
        <?php else: ?>
            <?=SITE_TITLE;?>
        <?php endif; ?>
    </title>
<script Language="JavaScript">
    function setmode(m)
    {
        location='?m='+m;
    }
</script>
<style type="text/css">
body { background:#4F5D55;}
.b1 {
	background: linear-gradient(#414B5E, #000000);
	border: 0px inset #000000;
	border-radius:  8px;
	color: #ffffff;
	font-weight:600;
	cursor:pointer;
	height:25px;
}
.b2 {
	background: linear-gradient(#5D1313, #000000);
	border: 0px inset #000000;
	border-radius:  8px;
	color: #ffffff;
	font-weight:600;
	cursor:pointer;
	height:25px;
}
.menu {
    height: 200px;
    width: 200px;
	overflow: hidden;
	background: #A0AEA6;
    border-radius: 5px;
    margin:5px;
    padding:3px;
    box-shadow: 0 0 5px 1px;
}
.login {
    height: 150px;
    width: 300px;
	overflow: hidden;
	background: #A0AEA6;
    border-radius: 5px;
    margin:5px;
    padding:3px;
    box-shadow: 0 0 5px 1px;
}
tr:hover {
    background: #B9CFB1;
    cursor:pointer;
   }
.news {
    position:absolute;
    height: 80%;
    width: 500px;
    left:250px;
    top:5px;
	overflow: hidden;
	background: #A0AEA6;
    border-radius: 5px;
    margin:5px;
    padding:3px;
    box-shadow: 0 0 5px 1px; 
}   
.msg {
    position:absolute;
    height: 50%;
    width: 500px;
    left:250px;
    top:5px;
	overflow: hidden;
	background: #A0AEA6;
    border-radius: 5px;
    margin:5px;
    padding:3px;
    box-shadow: 0 0 5px 1px; 
}   
.friends {
    position:absolute;
    height: 50%;
    width: 500px;
    left:250px;
    top:5px;
	overflow: hidden;
	background: #A0AEA6;
    border-radius: 5px;
    margin:5px;
    padding:3px;
    box-shadow: 0 0 5px 1px; 
}   
</style>
</head>
<body>
