<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        <?php if(isset($title)):?>
            <?=$title;?>
        <?php else: ?>
            <?=SITE_TITLE;?>
        <?php endif; ?>
    </title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.7/slick.css"/>
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.7/slick.min.js"></script>

<script type="text/javascript" src="/js/script.js"></script>
<link rel="stylesheet" type="text/css" href="/css/style1.css">
</head>
<body onload=loadf()>
